FROM php:8.2-cli

WORKDIR /app

# Installer dépendances
RUN apt-get update && apt-get install -y \
    unzip \
    git \
    curl \
    libpq-dev \
    && docker-php-ext-install pdo pdo_pgsql

# Installer Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Copier projet
COPY . .

# Installer Laravel
RUN composer install --no-dev --optimize-autoloader

# Port Render
EXPOSE 10000

CMD php artisan serve --host=0.0.0.0 --port=10000